export const PROMPT_CATEGORIES = [
  'everyday',
  'debugging',
  'documentation',
  'testing',
  'package_management',
  'ai_native',
  'context',
  'fun',
  'start_scratch',
] as const;

export const PROMPT_KEYS = {
  everyday: [
    'refactor',
    'add_test',
    'add_types',
    'mock_data',
    'convert_modules',
    'async_await',
    'data_class',
  ],
  debugging: [
    'fix_error',
    'profiling',
    'undefined_value',
    'memory_leak',
    'add_logging',
    'race_conditions',
    'trace_execution',
  ],
  documentation: [
    'readme',
    'add_comments',
    'api_docs',
    'docstrings',
  ],
  testing: [
    'integration_tests',
    'mock_fetch',
    'migrate_test_suite',
    'property_based',
    'slow_network',
    'backward_compatibility',
    'mock_external_api',
  ],
  package_management: [
    'upgrade_linter',
    'changelog',
    'remove_dependencies',
    'check_maintenance',
    'auto_updates',
  ],
  ai_native: [
    'feature_ideas',
    'tech_debt',
    'find_duplicates',
    'refactor_clusters',
    'scope_issue',
    'reusable_plugin',
    'parallel_processing',
  ],
  context: [
    'status_update',
    'summarize_changes',
  ],
  fun: [
    'confetti',
    'dev_joke',
    'cli_game',
    'dark_mode_easter_egg',
    'github_app',
  ],
  start_scratch: [
    'repo_overview',
    'init_express',
    'monorepo_setup',
    'python_bootstrap',
    'chrome_extension',
    'web_scraper',
  ],
};
